version: "2"

services:
  vstu-judge-back:
    ports:
        - "7071:7071"
    build: "./vstu-judge-back"
    
  vstu-judge-queue:
    ports:
        - "7070:7070"
    build: "./vstu-judge-queue"
    image: "deeplymax/vstu-judge-queue"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    depends_on:
      - "vstu-judge-etcd-db"
      - "vstu-judge-redis-db"
      - "vstu-judge-mongo-db"

  vstu-judge-etcd-db:
    image: "quay.io/coreos/etcd:v2.3.3"
    networks:
      default:
        aliases:
          - "vstu-judge-discovery-db"
  vstu-judge-redis-db:
    image: "redis:3.0.7"
    networks:
      default:
        aliases:
          - "vstu-judge-queue-db"
          - "vstu-judge-state-db"
  vstu-judge-mongo-db:
    image: "mongo:3.2.6"
    networks:
      default:
        aliases:
          - "vstu-judge-task-db"
          - "vstu-judge-problem-db"
