version: "2"

services:
  vstu-judge-queue:
    build: "."
    image: "deeplymax/vstu-judge-queue"
    depends_on:
      - "vstu-judge-etcd-db"
      - "vstu-judge-redis-db"
      - "vstu-judge-mongo-db"

  vstu-judge-etcd-db:
    image: "quay.io/coreos/etcd:v2.3.3"
    networks:
      default:
        aliases:
          - "vstu-judge-discovery-db"
  vstu-judge-redis-db:
    image: "redis:3.0.7"
    networks:
      default:
        aliases:
          - "vstu-judge-queue-db"
  vstu-judge-mongo-db:
    image: "mongo:3.2.6"
    networks:
      default:
        aliases:
          - "vstu-judge-task-db"
